networks:
  workflow-net:
    name: workflow-net
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-quiz
    restart: always
    environment:
      MYSQL_DATABASE: mw_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: mmh-test
      MYSQL_ROOT_PASSWORD: mmh-test
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - workflow-net

  quiz-generator-api:
    build:
      context: ./lambdas/generateQuiz/src
      dockerfile: Dockerfile.dev
    container_name: quiz-generator-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPEN_API_KEY}
      - AWS_PROFILE=escco
      - S3_BUCKET=quiz-src-bucket-ky-dev
    env_file:
      - .env
    volumes:
      - ./lambdas/generateQuiz/src:/app
      - ./lambdas/generateQuiz/app:/app/app
      - ~/.aws:/root/.aws:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - workflow-net
volumes:
  mysql-data:
